### ISSUE TITLE
pylint should be used to clean up many issues in the orvsd_central module

### ISSUE THREAD

**Issue by Chetco** [orvsd/orvsd_central#117]

**Comment by brutal-chaos** [comment]
When I submit code, I usually try and remember to run flake8. What else does pylint catch?

**Comment by brutal-chaos** [comment]
@Chetco ^

**Comment by Chetco** [comment]
@brutal-chaos it helps to detect unused code, and many harmless things which can be disabled. It identifies every module/class/function/etc that does not contain a docstring, for example.

**Comment by brutal-chaos** [comment]
@Chetco ohneat! I'll have to give it a try

**Comment by brutal-chaos** [comment]
After looking through, this doesn't seem to add much value over flake8 and actually causes one to look through more output (or turn off many features...basically turning it into flake8)

**Comment by Chetco** [comment]
In the meantime I will think of a more specific issue for this.
