### ISSUE TITLE
Collapse Course and CourseDetail into one Model

### ISSUE THREAD

**Issue by justinnoah** [orvsd/orvsd_central#152]
We need to collapse Course and CourseDetail into one table, Course. The model would have:
`Name, Shortname, Version, Moodle Version, Serial, File Path, License, and Source`. This would represent one file which is one course. The details of the course including intended moodle version and file location are all included in said table.

SiteCourse would then be updated to have `SiteFK, CourseFK, and Active`. Future additions to the columns would be useful for having details related to the courses use on a site. The current celery_task_id needs to be removed as we don't use it and there are other, better methods for tracking the task. Another issue should be opened to handle course restore tracking.

**Comment by Kennric** [comment]
Yes, I think this is sensible. I forget the original rationale for having a detail model, other than following the Site/SiteDetail example.
