### ISSUE TITLE
Flash messages should be colored based on status

### ISSUE THREAD

**Issue by justinnoah** [orvsd/orvsd_central#53]
Something like:

Success: Green
Warning: Yellow
Error     : Red

**Comment by brutal-chaos** [comment]
Blocked on #120

**Comment by Chetco** [comment]
@brutal-chaos no longer blocked?

**Comment by brutal-chaos** [comment]
@Chetco good catch, unblocked

**Comment by justinnoah** [comment]
http://flask.pocoo.org/docs/0.10/api/#flask.flash shows that there is a category parameter that I'll use for coloring the messages.
