### ISSUE TITLE
Store admin email addresses

### ISSUE THREAD

**Issue by Kennric** [orvsd/orvsd_central#82]
Currently OC stores a single admin email for each site, as reported by moodle's CFG->admin. This is not a useful or meaningful address. Instead, store a list of all users that have the 'admin' role on a site. The siteinfo plugin (webservice version) will return a dictionary site_admins: {name: email_address, ...} - OC should store these in a convenient form for easily generating a mailing list to alert admins of system issues.

**Comment by Chetco** [comment]
@brutal-chaos Has this been solved by the interface to the siteinfo plugin?

**Comment by brutal-chaos** [comment]
@Chetco 

The code is at - it.osuosl.org:orvsd/moodle_siteinfo
On branch - moodle-2.7/feature/17031_siteinfo_webservice

for future reference. Currently it does not look like that has been implemented yet

**Comment by brutal-chaos** [comment]
Creating a migration for this
